[package]
name = "gdrivefs"
version = "0.1.0"
authors = ["jonallie"]

[dependencies]
docopt = "0.6"
env_logger = "0.3"
fuse = { git = "https://github.com/zargony/rust-fuse" }
google-drive3 = "*"
hyper = "0.7"
inth-oauth2 = "0.7"
libc = "0.2"
log = "0.3"
lru_time_cache = "0.2"
rustc-serialize = "0.3"
time = "0.1"
urlparse = "0.7"
yup-oauth2 = "0.5"
